name: CI
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: radekadamczewski/rabudget-ui:latest
          build-args: |
            VUE_APP_AUTH_AUTHORITY=${{ secrets.VUE_APP_AUTH_AUTHORITY }}
            VUE_APP_AUTH_REDIRECT_URI=${{ secrets.VUE_APP_AUTH_REDIRECT_URI }}
            VUE_APP_AUTH_POPUP_REDIRECT_URI=${{ secrets.VUE_APP_AUTH_POPUP_REDIRECT_URI }}
            VUE_APP_AUTH_POST_LOGOUT_REDIRECT_URI=${{ secrets.VUE_APP_AUTH_POST_LOGOUT_REDIRECT_URI }}
            VUE_APP_AUTH_SILENT_REDIRECT_URI=${{ secrets.VUE_APP_AUTH_SILENT_REDIRECT_URI }}
