name: CI
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          VUE_APP_AUTH_AUTHORITY: ${{ secrets.VUE_APP_AUTH_AUTHORITY }}
          VUE_APP_AUTH_REDIRECT_URI: ${{ secrets.VUE_APP_AUTH_REDIRECT_URI }}
          VUE_APP_AUTH_POPUP_REDIRECT_URI: ${{ secrets.VUE_APP_AUTH_POPUP_REDIRECT_URI }}
          VUE_APP_AUTH_POST_LOGOUT_REDIRECT_URI: ${{ secrets.VUE_APP_AUTH_POST_LOGOUT_REDIRECT_URI }}
          VUE_APP_AUTH_SILENT_REDIRECT_URI: ${{ secrets.VUE_APP_AUTH_SILENT_REDIRECT_URI }}
        with:
          name: radekadamczewski/rabudget-ui
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: VUE_APP_AUTH_AUTHORITY,VUE_APP_AUTH_REDIRECT_URI,VUE_APP_AUTH_POPUP_REDIRECT_URI,VUE_APP_AUTH_POST_LOGOUT_REDIRECT_URI,VUE_APP_AUTH_SILENT_REDIRECT_URI
